- name: Gather facts from ALL hosts (regardless of limit or tags)
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: True
  when: hostvars[item]['ansible_hostname'] is not defined
  with_items: "{{ groups['hosts'] }}"
