apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    mojix.service: mysql
  name: mysql
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mysql:8
    generation: null
    importPolicy: {}
    name: "8"
status:
  dockerImageRepository: ""
