apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-claim0 
spec:
  capacity:
    storage: 30Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /apps/exports/mojix/mysql-vol
    server: dclpcmpa01
  persistentVolumeReclaimPolicy: Retain
