apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    mojix.service: zookeeper
  name: zookeeper
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: zookeeper:3.4.10
    generation: null
    importPolicy: {}
    name: 3.4.10
status:
  dockerImageRepository: ""
