apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper-claim0 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /apps/exports/mojix/zookeeper-data-vol
    server: dclpcmpa01
  persistentVolumeReclaimPolicy: Retain
