apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-claim0 
spec:
  capacity:
    storage: 20Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path:  
    server:  
  persistentVolumeReclaimPolicy: Retain
