apiVersion: v1
kind: PersistentVolume
metadata:
  name: proxy-claim1 
spec:
  capacity:
    storage: 50Mi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /apps/exports/mojix/proxy-vol
    server: dclpcmpa01
  persistentVolumeReclaimPolicy: Retain
