apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    mojix.service: kafka
  name: kafka
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: mojix/kafka:v1.1.0
    generation: null
    importPolicy: {}
    name: v1.1.0
status:
  dockerImageRepository: ""
