apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    mojix.service: kafka
  name: kafka
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    mojix.service: kafka
  type: NodePort
