version: "3.3"

networks:
  iot:
    driver: overlay
    attachable: true

services:

  actionprocessor:
    image: mojix/riot-core-bridges:v6.45.0
    environment:
      MEM_XMS: 2g
      MEM_XMX: 2g
      VIZIX_BRIDGE_TYPE: actionprocessor
      VIZIX_KAFKA_SERVERS: kafka:9092
    networks:
      - iot
    deploy:
      endpoint_mode: dnsrr
      replicas: 1
      resources:
        limits:
          memory: 3g
      placement:
        constraints:
          - node.labels.host == ##HOST_LABEL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 50s
      timeout: 10s
      retries: 2
    logging:
      driver: syslog
      options:
        syslog-address: udp:// ##PAPERTRAIL_LINK
        tag: actionprocessor
