version: "3.3"

networks:
  iot:
    driver: overlay
    attachable: true

services:

  flow:
    image: mojix/flow:v1.0.1
    hostname: flow
    volumes:
      - /data/flows:/flows
    #environment:
      #- MAX_OLD_SPACE=8192
    networks:
      - iot
    deploy:
      resources:
        limits:
          memory: 2G
      placement:
        constraints:
          - node.labels.host == ##HOST_LABEL
    logging:
      driver: syslog
      options:
        syslog-address: udp:// ##PAPERTRAIL_LINK
        tag: flow
