version: "3.3"

networks:
  iot:
    driver: overlay
    attachable: true

services:

  mysql:
    image: mysql:8
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    command: 
      - --max_allowed_packet=1024M 
      - --max_connections=7000 
      - --interactive_timeout=3600 
      - --wait_timeout=3600 
      - --lower_case_table_names=0 
      - --net_write_timeout=3600 
      - --net_read_timeout=3600 
      - --innodb_lock_wait_timeout=600 
      - --skip-name-resolve 
      - --innodb_thread_sleep_delay=60000000 
      - --default-authentication-plugin=mysql_native_password 
      - --character-set-server=utf8 
      - --collation-server=utf8_bin
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=riot_main
      - MYSQL_ROOT_PASSWORD= ##VIZIX_DB_PASSWORD
    networks:
      - iot
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - node.labels.host == ##HOST_LABEL
      resources:
        limits:
          memory: 1g
    logging:
      driver: syslog
      options:
        syslog-address: udp:// ##PAPERTRAIL_LINK
        tag: mysql
