apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-claim0 
spec:
  capacity:
    storage: 500Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /apps/exports/mojix/mongo-vol
    server: dclpcmpa01
  persistentVolumeReclaimPolicy: Retain
