apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    mojix.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    mojix.service: mongo
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        mojix.service: mongo
    spec:
      containers:
      - args:
        - --storageEngine=wiredTiger
        - --journal
        - --slowms=5000
        - --profile=1
        - --cpu
        - --dbpath=/data/db
        - --directoryperdb
        - --wiredTigerCacheSizeGB=16
        - --wiredTigerDirectoryForIndexes
        - --bind_ip_all
        - --auth
        image: mongo:4.0.3
        name: mongo
        ports:
        - containerPort: 27017
        resources:
          requests: 
            memory: 32Gi 
          limits:
            memory: 32Gi 
        volumeMounts:
        - mountPath: /data/db
          name: mongo-claim0
      hostname: mongo
      restartPolicy: Always
      volumes:
      - name: mongo-claim0
        persistentVolumeClaim:
          claimName: mongo-claim0
  triggers:
    - type: ConfigChange
