apiVersion: v1
kind: Service
metadata:
  labels:
    mojix.service: ui
  name: ui
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    mojix.service: ui
status:
  loadBalancer: {}
