apiVersion: v1
kind: Service
metadata:
  labels:
    mojix.service: flow
  name: flow
spec:
  ports:
  - name: "1880"
    port: 1880
    targetPort: 1880
  selector:
    mojix.service: flow
status:
  loadBalancer: {}
