apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    mojix.service: flow
  name: flow
spec:
  replicas: 1
  selector:
    mojix.service: flow
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        mojix.service: flow
    spec:
      spec:
      containers:
      - image: mojix/flow:latest
        name: flow
        resources: {}
        volumeMounts:
        - mountPath: /flows
          name: flow-claim0
      hostname: flow
      restartPolicy: Always
      volumes:
      - name: flow-claim0
        persistentVolumeClaim:
          claimName: flow-claim0
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - flow
        from:
          kind: ImageStreamTag
          name: flow:latest
      type: ImageChange
