apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    mojix.service: k2m
  name: k2m
spec:
  replicas: 1
  selector:
    mojix.service: k2m
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        mojix.service: k2m
    spec:
      containers:
      - env:
        - name: VIZIX_BRIDGE_TYPE
          value: k2mbridge
        - name: VIZIX_KAFKA_SERVERS
          value: kafka:9092
        - name: VIZIX_MQTTHOST
          value: mqtt
        image: mojix/riot-core-bridges:latest
        name: k2m
        resources: {}
      hostname: k2m
      restartPolicy: Always
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - k2m
        from:
          kind: ImageStreamTag
          name: riot-core-bridges:latest
      type: ImageChange
