apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    mojix.service: m2k
  name: m2k
spec:
  replicas: 1
  selector:
    mojix.service: m2k
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        mojix.service: m2k
    spec:
      containers:
      - env:
        - name: VIZIX_BRIDGE_TYPE
          value: m2kbridge
        - name: VIZIX_KAFKA_SERVERS
          value: kafka:9092
        - name: VIZIX_MQTTHOST
          value: mqtt
        image: mojix/riot-core-bridges:latest
        name: m2k
        resources: {}
      hostname: m2k
      restartPolicy: Always
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - m2k
        from:
          kind: ImageStreamTag
          name: riot-core-bridges:latest
      type: ImageChange
