apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    mojix.service: mqtt
  name: mqtt
spec:
  ports:
  - name: "1883"
    port: 1883
    targetPort: 1883
  - name: "18083"
    port: 18083
    targetPort: 18083
  selector:
    mojix.service: mqtt
status:
  loadBalancer: {}
