apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
  labels:
    mojix.service: mqtt
  name: mqtt
spec:
  replicas: 1
  selector:
    mojix.service: mqtt
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        mojix.service: mqtt
    spec:
      containers:
      - env:
        - name: EMQ_LISTENER__API__MGMT
          value: 0.0.0.0:18080
        - name: EMQ_MQTT__CLIENT__ENABLE_STATS
          value: "on"
        - name: EMQ_MQTT__CLIENT__IDLE_TIMEOUT
          value: 120s
        - name: EMQ_MQTT__MAX_PACKET_SIZE
          value: 512000KB
        - name: EMQ_MQTT__MQUEUE__MAX_LENGTH
          value: "0"
        - name: EMQ_MQTT__SESSION__ENABLE_STATS
          value: "on"
        - name: EMQ_MQTT__SESSION__EXPIRY_INTERVAL
          value: 5s
        - name: EMQ_MQTT__SESSION__MAX_INFLIGHT
          value: "1000"
        image: mojix/emqtt:latest
        name: mqtt
        ports:
        - containerPort: 1883
        - containerPort: 18083
        resources: {}
      hostname: mqtt
      restartPolicy: Always
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - mqtt
        from:
          kind: ImageStreamTag
          name: emqtt:latest
      type: ImageChange
