apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <namespace>
  name: mapreduce
  labels:
    mojix.service: mapreduce
spec:
  replicas: 1
  selector:
    matchLabels:
      mojix.service: mapreduce
  template:
    metadata:
      creationTimestamp: null
      labels:
        mojix.service: mapreduce
    spec:
      containers:
      - name: mapreduce
        resources:
          limits:
            memory: 2000Mi
          requests:
            memory: 2000Mi
        image: mojix/vizix-retail-mapreduce:canary_6.57.x
        imagePullPolicy: "Always"
        env:
          - name: MEM_XMS
            value: "1900m"
          - name: MEM_XMX
            value: "1900m"
          - name: VIZIX_BRIDGE_TYPE
            value: "mongoingestor"
          - name: VIZIX_KAFKA_SERVERS
            value: "kafka1:9092,kafka2:9092,kafka3:9092"
          - name: VIZIX_MONGO_WRITE_CONCERN
            value: "ACKNOWLEDGED"
          - name: VIZIX_KAFKA_TOPICS
            value: "___v1___analytics___mapreduce"
          - name: VIZIX_MONGO_URI
            value: "mongodb://admin:<password>@mongo1:27017,mongo2:27017,mongo3:27017/?authSource=admin"
          - name: VIZIX_MONGO_WRITE_CONCERN
            value: "ACKNOWLEDGED"
          - name: VIZIX_MONGO_COLLECTION
            value: "mr_items_vertex_[TENANT]" 
          - name: VIZIX_MONGO_MULTIDATABASE
            value: "true"
          - name: VIZIX_GROUP_ID
            value: "analytics_mapreduce"
          - name: VIZIX_KAFKA_OFFSET_RESET
            value: "latest"
          - name: VIZIX_PROCESS_MODE
            value: SERIAL
          - name: VIZIX_RETAIL_STATUSES
            value: "ACTIVE,CONTAINER_CLOSED,DAMAGED,DESTROYED,DISPENSED,DISPOSED,ENCODED,EXPIRED,IN_PROGRESS,IN_TRANSIT,INACTIVE,MISSING,NO_PEDIGREE_MATCH,NON_SELLABLE_OTHER,PARTIALLY_DISPENSED,RECALLED,RESERVED,RETAIL_SOLD,RETURNED,SELLABLE_ACCESSIBLE,SELLABLE_NOT_ACCESSIBLE,STOLEN,UNKNOWN"
      imagePullSecrets:
        - name: mojix-registry
      hostname: mapreduce
      restartPolicy: Always
