{
 "title": "Rate Metrics",
 "description": "Kafka Metrics",
 "tags": [ "kafka" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "___v1___data1",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(vizix_kafka_offset{topic=\"___v1___data1\"})"
    }
   ]
  },
  {
   "title": "___v1___data2",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(vizix_kafka_offset{topic=\"___v1___data2\"})"
    }
   ]
  },
  {
   "title": "Total Lag RP",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"rulesProcessor-___v1___data1\",topic=\"___v1___data1\"})"
    }
   ]
  },
  {
   "title": "Total Lag MOI",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"mongoIngestor-___v1___data2\",topic=\"___v1___data2\"})"
    }
   ]
  },
  {
   "title": "Total Lag AP mosquitto-1883",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"actionProcessor-mosquitto-1883\",topic=\"___v1___action___mosquitto-1883\"})"
    }
   ]
  },
  {
   "title": "Rules Processor Lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{topic=\"___v1___data1\"})",
     "legendFormat": "from server"
    },
    {
     "expr": "sum(vizix_kafka_lag{topic=\"___v1___data1\"})",
     "legendFormat": "from stream app"
    }
   ]
  },
  {
   "title": "Rules Processor Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"___v1___data1\"} [1m]))"
    }
   ]
  },
  {
   "title": "Rules Processor Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"___v1___errors___rulesProcessor\"})"
    }
   ]
  },
  {
   "title": "Mongo Ingestor Lag",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"mongoIngestor-___v1___data2\",topic=\"___v1___data2\"})",
     "legendFormat": "from server"
    },
    {
     "expr": "sum(vizix_kafka_lag{topic=\"___v1___data2\"})",
     "legendFormat": "from stream app"
    }
   ]
  },
  {
   "title": "Mongo Ingestor Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=\"___v1___data2\"}[1m]))"
    }
   ]
  },
  {
   "title": "Mongo Ingestor Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"___v1___errors___mongoinjector\"})"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "things" }
   ],
   "targets": [
    { "expr": "vizix_thing_cache_size" }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vizix_thing_cache_hit_rate" }
   ]
  },
  {
   "title": "Cache load count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vizix_thing_cache_load_count" }
   ]
  },
  {
   "title": "Action Processor Lag",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"actionProcessor-mosquitto-1883\",topic=\"___v1___action___mosquitto-1883\"})"
    }
   ]
  },
  {
   "title": "Action Processor Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vizix_kafka_trate{topic=\"___v1___action___mosquitto-1883\"}"
    }
   ]
  }
 ]
}