{
 "title": "System Load",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage per Container on its Host",
   "type": "graph",
   "description": "100% is the top CPU shares per host. Meaning, if RulesProcessor is ~90%, that is the 90% of the available CPU shares on the host it's running.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"vizix_mongoinjector\"}[1m]))  * 100 / 8",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"vizix_rulesprocessor\"}[1m]))  * 100 / 8",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"vizix_actionprocessor\"}[1m]))  * 100 / 8",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=\"vizix_services\"}[1m]))  * 100 / 8",
     "legendFormat": "{{ name }}"
    },
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image=\"mongo:3.6.5\"}[1m]))  * 100 / 8",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "KohlsP1 DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_load1{instance=\"10.0.0.35:9100\",job=\"node_exporter\"}[1m])) * 100",
     "legendFormat": "Load 1s"
    },
    {
     "expr": "sum(rate(node_load5{instance=\"10.0.0.35:9100\",job=\"node_exporter\"}[1m])) * 100",
     "legendFormat": "Load 5s"
    },
    {
     "expr": "sum(rate(node_load15{instance=\"10.0.0.35:9100\",job=\"node_exporter\"}[1m])) * 100",
     "legendFormat": "Load 15s"
    }
   ]
  },
  {
   "title": "KohlsP2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_load1{instance=\"10.0.0.39:9100\",job=\"node_exporter\"}[1m])) * 100",
     "legendFormat": "Load 1s"
    },
    {
     "expr": "sum(rate(node_load5{instance=\"10.0.0.39:9100\",job=\"node_exporter\"}[1m])) * 100",
     "legendFormat": "Load 5s"
    },
    {
     "expr": "sum(rate(node_load15{instance=\"10.0.0.39:9100\",job=\"node_exporter\"}[1m])) * 100",
     "legendFormat": "Load 15s"
    }
   ]
  },
  {
   "title": "KohlsP3",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_load1{instance=\"10.0.0.38:9100\",job=\"node_exporter\"}[1m]))  * 100",
     "legendFormat": "Load 1s"
    },
    {
     "expr": "sum(rate(node_load5{instance=\"10.0.0.38:9100\",job=\"node_exporter\"}[1m]))  * 100",
     "legendFormat": "Load 5s"
    },
    {
     "expr": "sum(rate(node_load15{instance=\"10.0.0.38:9100\",job=\"node_exporter\"}[1m]))  * 100",
     "legendFormat": "Load 15s"
    }
   ]
  },
  {
   "title": "KohlsP4",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_load1{instance=\"10.0.0.36:9100\",job=\"node_exporter\"}[1m]))  * 100",
     "legendFormat": "Load 1s"
    },
    {
     "expr": "sum(rate(node_load5{instance=\"10.0.0.36:9100\",job=\"node_exporter\"}[1m]))  * 100",
     "legendFormat": "Load 5s"
    },
    {
     "expr": "sum(rate(node_load15{instance=\"10.0.0.36:9100\",job=\"node_exporter\"}[1m]))  * 100",
     "legendFormat": "Load 15s"
    }
   ]
  },
  {
   "title": "Kohls P1 Mongo + MQTT + UI + PROXY",
   "type": "singlestat",
   "description": "MQTT UI PROXY",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"10.0.0.35:9100\"} - node_memory_MemAvailable_bytes{instance=~\"10.0.0.35:9100\"}) / node_memory_MemTotal_bytes{instance=~\"10.0.0.35:9100\"}) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Kohls P2 + Mongo Injector + Services",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"10.0.0.39:9100\"} - node_memory_MemAvailable_bytes{instance=~\"10.0.0.39:9100\"}) / node_memory_MemTotal_bytes{instance=~\"10.0.0.39:9100\"}) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Kohls P3 + Rules + Action + k2m + m2k",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"10.0.0.38:9100\"} - node_memory_MemAvailable_bytes{instance=~\"10.0.0.38:9100\"}) / node_memory_MemTotal_bytes{instance=~\"10.0.0.38:9100\"}) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Kohls P4 + http + ftp + kafka + mysql + tf + zoo",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"10.0.0.36:9100\"} - node_memory_MemAvailable_bytes{instance=~\"10.0.0.36:9100\"}) / node_memory_MemTotal_bytes{instance=~\"10.0.0.36:9100\"}) * 100",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "HTTPBridge Networking",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_hbridge\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network UP Transmit"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_hbridge\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network DOWN Transmit"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_hbridge\", interface=\"eth1\"}[1m]))",
     "legendFormat": "PHY Network UP"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_hbridge\", interface=\"eth1\"}[1m]))",
     "legendFormat": "PHY Network DOWN"
    }
   ]
  },
  {
   "title": "TransformBridge Networking",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_transformbridge\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network UP Transmit"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_transformbridge\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network DOWN Transmit"
    }
   ]
  },
  {
   "title": "RP Networking",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_rulesprocessor\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network UP Transmit"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_rulesprocessor\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network DOWN Transmit"
    }
   ]
  },
  {
   "title": "MOI Networking",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_mongoinjector\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network UP Transmit"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_mongoinjector\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network DOWN Transmit"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_mongoinjector\", interface=\"eth1\"}[1m]))",
     "legendFormat": "Network PHY to MONGO"
    }
   ]
  },
  {
   "title": "Mongo",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"mongo\", interface=\"enP1p0s2\"}[1m]))",
     "legendFormat": "Network UP Transmit"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{name=\"mongo\", interface=\"enP1p0s2\"}[1m]))",
     "legendFormat": "Network DOWN Transmit"
    }
   ]
  },
  {
   "title": "MySQL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_mysql\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network UP Transmit"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_mysql\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network DOWN Transmit"
    }
   ]
  },
  {
   "title": "Kafka Networking",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_kafka\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network UP Transmit"
    },
    {
     "expr": "- sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_service_name=~\"vizix_kafka\", interface=\"eth0\"}[1m]))",
     "legendFormat": "Network DOWN Transmit"
    }
   ]
  },
  {
   "title": "Docker Memory History",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image=\"mongo:3.6.5\"})",
     "legendFormat": "{{ mongo }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"vizix_rulesprocessor\"})",
     "legendFormat": "{{ vizix_rules_processor }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"vizix_mongoinjector\"})",
     "legendFormat": "{{ vizix_mongo_injector }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"vizix_transformbridge\"})",
     "legendFormat": "{{ vizix_transform_bridge }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"vizix_actionprocessor\"})",
     "legendFormat": "{{ vizix_actionprocessor }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"vizix_kafka\"})",
     "legendFormat": "{{ kafka }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"vizix_services\"})",
     "legendFormat": "{{ services }}"
    },
    {
     "expr": "sum by (name)(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=\"vizix_hbridge\"})",
     "legendFormat": "{{ vizix_httpbridge }}"
    },
    {
     "expr": "sum by (name) (container_memory_cache{image=\"mongo:3.6.5\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "{{ mongo cache}}"
    },
    {
     "expr": "sum by (name) (container_memory_cache{image=\"mongo:3.6.5\",container_label_org_label_schema_group=\"\"} + container_memory_usage_bytes{image=\"mongo:3.6.5\"} )",
     "legendFormat": "{{ mongo total }}"
    }
   ]
  }
 ]
}