apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    mojix.service: services
  name: services
spec:
  replicas: 1
  selector:
    mojix.service: services
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        mojix.service: services
    spec:
      containers:
      - env:
        - name: MEM_XMS
          value: 2g
        - name: MEM_XMX
          value: 4g
        - name: VIZIX_AUTHENTICATION_MODE
          value: nativeAuthentication
        - name: VIZIX_BROKER_CONNECTION_WAIT
          value: "false"
        - name: VIZIX_CONNECTION_URL
          value: jdbc:mysql://mysql:3306/riot_main?useSSL=false&amp;characterEncoding=UTF-8
        - name: VIZIX_DB_DIALECT
          value: org.hibernate.dialect.MySQLDialect
        - name: VIZIX_DB_DRIVER
          value: com.mysql.jdbc.Driver
        - name: VIZIX_DB_PASSWORD
          value: control123!
        - name: VIZIX_DB_SCHEMA
          value: riot_main
        - name: VIZIX_HAZELCAST_DISTRIBUTED_ENABLE
          value: "false"
        - name: VIZIX_HAZELCAST_NATIVE_CLIENT_ADDRESS
          value: hazelcast
        - name: VIZIX_HOME_SERVICES
          value: /jar
        - name: VIZIX_KAFKA_ENABLED
          value: "true"
        - name: VIZIX_KAFKA_SERVERS
          value: kafka:9092
        - name: VIZIX_KAFKA_ZOOKEEPER
          value: zookeeper:2181
        - name: VIZIX_MONGO_DB
          value: riot_main
        - name: VIZIX_MONGO_PASSWORD
          value: mutton_vitrify_brother_detain
        - name: VIZIX_MONGO_PRIMARY
          value: mongo:27017
        - name: VIZIX_MONGO_USERNAME
          value: admin
        - name: VIZIX_MQTT_HOST
          value: mqtt
        image: mojix/riot-core-services
        name: services
        resources: {}
        #volumeMounts:
        #- mountPath: /usr/local/tomcat/endorsed
        #  name: services-claim0
        #- mountPath: /data
        #  name: services-claim1
      hostname: services
      restartPolicy: Always
      #volumes:
      #- name: services-claim0
      #  persistentVolumeClaim:
      #    claimName: services-claim0
      #- name: services-claim1
      #  persistentVolumeClaim:
      #    claimName: services-claim1
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - services
        from:
          kind: ImageStreamTag
          name: riot-core-services:latest
      type: ImageChange
