apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    mojix.service: hbridge
  name: hbridge
spec:
  replicas: 1
  selector:
    mojix.service: hbridge
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        mojix.service: hbridge
    spec:
      containers:
      - env:
        - name: VIZIX_BRIDGE_TYPE
          value: httpbridge
        - name: VIZIX_KAFKA_SERVERS
          value: kafka:9092
        image: mojix/riot-core-bridges:latest
        name: hbridge
        resources: {}
      hostname: hbridge
      restartPolicy: Always
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - hbridge
        from:
          kind: ImageStreamTag
          name: riot-core-bridges:latest
      type: ImageChange
