apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider openshift
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    mojix.service: hbridge
  name: hbridge
spec:
  ports:
  - name: "8080"
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    mojix.service: hbridge
  sessionAffinity: None
status:
  loadBalancer: {}
